# This field keeps the timestamp of when 'repo bootstrap' was executed.
# This timestamp is being used by the pre-push hook to check only the commits
# that happened after so that it is easier to migrate existing projects to SF.
# You can modify the timestamp manually in case there is a need.
salsaflow_enabled_timestamp: "2015-06-08T08:40:45.923692728+02:00"

#-- ISSUE TRACKER
issue_tracker: "jira"
jira:
  server_url: "https://jira.salsitasoft.com"
  project_key: "SF"

#-- CODE REVIEW TOOL
code_review_tool: "github"
